--1
CREATE OR REPLACE TRIGGER EMPANTIDELETE AFTER DELETE ON EMP
BEGIN
    RAISE_APPLICATION_ERROR(-20001,'NIE MOZNA USUWAC REKORDOW Z TABELI EMP');
END;

--SAVEPOINT SAVE1;

SELECT * FROM EMP;

DELETE FROM EMP;

--ROLLBACK TO SAVEPOINT SAVE1;

--2
CREATE OR REPLACE TRIGGER CHECKSAL AFTER INSERT OR UPDATE ON EMP
    FOR EACH ROW
    BEGIN
        IF :NEW.SAL < 1000 THEN
            RAISE_APPLICATION_ERROR(-20001,'PENSJA NIE MOZE BYC MNIEJSZA OD 1000');
        end if;
    END;

--SAVEPOINT SAVE2;

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(69,'TOMEK','CLERK','123',SYSDATE,10,0,10);

--ROLLBACK TO SAVEPOINT SAVE2;

--3
CREATE TABLE BUDZET (WARTOSC INT NOT NULL);

INSERT INTO BUDZET(WARTOSC)
SELECT SUM(SAL) FROM EMP;
COMMIT;

--SAVEPOINT SAVE3;

CREATE OR REPLACE TRIGGER CONTROL AFTER INSERT OR UPDATE OR DELETE ON EMP
    BEGIN
        UPDATE BUDZET SET WARTOSC = (SELECT SUM(SAL) FROM EMP);
    END;

UPDATE EMP SET SAL = 5000 WHERE EMPNO = 7521;
COMMIT;

--ROLLBACK TO SAVEPOINT SAVE3;

--4
CREATE OR REPLACE TRIGGER ZAD4 AFTER DELETE OR UPDATE OR INSERT ON EMP
    FOR EACH ROW
    BEGIN
        IF DELETING THEN
            IF :OLD.SAL > 0 THEN
                BEGIN
                    ROLLBACK;
                end;
            end if;
        end if;
        IF UPDATING THEN
            IF :OLD.ENAME != :NEW.ENAME THEN
                BEGIN
                    RAISE_APPLICATION_ERROR(-20001,'NIE WOLNO ZMIENIC NAZWISKA PRACOWNIKA!');
                end;
            end if;
        end if;

        IF INSERTING THEN
            IF :OLD.ENAME = :NEW.ENAME THEN
                BEGIN
                    RAISE_APPLICATION_ERROR(-20001,'NIE WOLNO WSTAWIC PRACOWNIKA KTORY INSTNIEJE!');
                end;
            end if;
        end if;
    END;

--5
CREATE OR REPLACE TRIGGER ZAD5 AFTER UPDATE OR DELETE ON EMP
    FOR EACH ROW
    BEGIN
        IF UPDATING THEN
            IF :NEW.SAL < :OLD.SAL THEN
                BEGIN
                    RAISE_APPLICATION_ERROR(-20001,'NIE WOLNO ZMNIEJSZAC PENSJI!');
                end;
            end if;
        end if;
        IF DELETING THEN
            BEGIN
                RAISE_APPLICATION_ERROR(-20001,'NIE WOLNO USUWAC PRACOWNIKOW!');
            END;
        end if;
    END;