--1
DECLARE LICZBA_PRACOWNIKOW INT;
BEGIN
    SELECT COUNT(*) INTO LICZBA_PRACOWNIKOW FROM EMP;
    DBMS_OUTPUT.PUT_LINE('W TABELI JEST ' || LICZBA_PRACOWNIKOW || ' OSOB!');
END;

--2
DECLARE LICZBA_PRACOWNIKOWZAD2 INT;
BEGIN
    SELECT COUNT(*) INTO LICZBA_PRACOWNIKOWZAD2 FROM EMP;

    --IF EXIST NIE ISTNIEJE!

    IF LICZBA_PRACOWNIKOWZAD2 < 16 THEN
        BEGIN
        INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES(22,'KOWALSKI','CLERK',123,SYSDATE,1000,NULL,10);
        DBMS_OUTPUT.PUT_LINE('WPROWADZONO KOWALSKIEGO!');
        END;
    ELSE

        BEGIN
            DBMS_OUTPUT.PUT_LINE('NIE WSTAWIONO DANYCH!');
        END;
    END IF;
END;
COMMIT;

--3
CREATE OR REPLACE PROCEDURE ADDDEPT(V_DEPTNO INT, V_DNAME VARCHAR2,V_LOC VARCHAR2) IS
    --MUSIMY TAK ZROBIC BO IF EXIST NIE ISTNIEJE!
    DEPTCOUNTNAME INT;
    DEPTCOUNTLOC INT;

BEGIN
    SELECT COUNT(*) INTO DEPTCOUNTNAME FROM DEPT WHERE DNAME = V_DNAME;
    SELECT COUNT(*) INTO DEPTCOUNTLOC FROM DEPT WHERE LOC = V_LOC;

    IF DEPTCOUNTLOC > 0 THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20201,'TAKA LOKALIZACJA DZIALU ISTNIEJE!');
        END;
    ELSIF DEPTCOUNTNAME > 0 THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20202,'TAKA NAZWA DZIALU ISTNIEJE!');
        END;
    ELSE
        BEGIN
            INSERT INTO DEPT(DEPTNO, DNAME, LOC)
            VALUES(V_DEPTNO,V_DNAME,V_LOC);
            DBMS_OUTPUT.PUT_LINE('WPROWADZONO DZIAL!');
        END;
    END IF;
END;

CALL ADDDEPT(10,'IT','WARSAW');
COMMIT;

--4
CREATE OR REPLACE PROCEDURE ADDEMP(V_DEPTNO INT, V_ENAME VARCHAR2) IS
    --NR DZIALU KTORY SPRAWDZAMY CZY ISTNIEJE
    DEPTCOUNTDEPTNO INT;
    --NR NOWEGO PRACOWNIKA
    EMPNONUM INT;
    --MIN PENSJA DLA DZIALU
    MINSAL FLOAT;
    --EXCEPTION
    NONUMBER EXCEPTION;

BEGIN
    --SPRAWDZANIE CZY DZIAL WYSTEPUJE W TABELI
    SELECT COUNT(*) INTO DEPTCOUNTDEPTNO FROM DEPT WHERE DEPTNO = V_DEPTNO;
    --NADAWANIE NRPRACOWNIKA
    SELECT MAX(EMPNO)+1 INTO EMPNONUM FROM EMP;
    --MINIMALNA PENSJA
    SELECT MIN(SAL) INTO MINSAL FROM EMP WHERE DEPTNO = V_DEPTNO;

    IF DEPTCOUNTDEPTNO = 0 THEN
        BEGIN
            RAISE NONUMBER;
        END;
    ELSE
        BEGIN
            INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (EMPNONUM,V_ENAME,'CLERK',402,SYSDATE,MINSAL,NULL,V_DEPTNO);
            DBMS_OUTPUT.PUT_LINE('DODANO NOWEGO PRACOWNIKA!');
        END;
    END IF;

EXCEPTION
    WHEN NONUMBER THEN
        RAISE_APPLICATION_ERROR(-20210,'PODANY DZIAL NIE ISTNIEJE!!');
END;

CALL ADDEMP(20,'SERAFINSKI');
COMMIT;

--5
CREATE TABLE MAGAZYN(
    IDPOZYCJI INTEGER PRIMARY KEY,
    NAZWA VARCHAR(20),
    ILOSC INTEGER
);

INSERT INTO MAGAZYN(IDPOZYCJI, NAZWA, ILOSC)
VALUES(1,'JABLKA',400);

INSERT INTO MAGAZYN(IDPOZYCJI, NAZWA, ILOSC)
VALUES(2,'GRUSZKI',300);

INSERT INTO MAGAZYN(IDPOZYCJI, NAZWA, ILOSC)
VALUES(3,'BANANY',200);

INSERT INTO MAGAZYN(IDPOZYCJI, NAZWA, ILOSC)
VALUES(4,'AWOKADO',5);


-- UPDATE MAGAZYN SET ILOSC = 400
-- WHERE IDPOZYCJI = 1;
-- UPDATE MAGAZYN SET ILOSC = 300
-- WHERE IDPOZYCJI = 2;
-- UPDATE MAGAZYN SET ILOSC = 200
-- WHERE IDPOZYCJI = 3;
-- UPDATE MAGAZYN SET ILOSC = 5
-- WHERE IDPOZYCJI = 4;

CREATE OR REPLACE PROCEDURE DECREMENTBY5 IS
    IDMAX INT;
    MAXILOSC INT;
BEGIN
    SELECT MAX(ILOSC) INTO MAXILOSC FROM MAGAZYN;
    SELECT IDPOZYCJI INTO IDMAX FROM MAGAZYN WHERE ILOSC = MAXILOSC;

    IF MAXILOSC <= 5 THEN
        BEGIN
            RAISE_APPLICATION_ERROR(-20250,'BLAD - PODANA WARTOSC PRZEWYZSZA ILOSC TOWARU O MAKSYMALNEJ ILOSCI!');
        END;
    ELSE
        BEGIN
            UPDATE MAGAZYN SET ILOSC = ILOSC-5 WHERE IDPOZYCJI = IDMAX;
        END;
    END IF;
END;

CALL DECREMENTBY5();
COMMIT;