--2
SELECT * FROM test WHERE Zawartosc = 12345
--0.449577

--3
CREATE NONCLUSTERED INDEX IX_TEST_ZAWARTOSC
ON TEST (Zawartosc);

SELECT * FROM test WHERE Zawartosc = 12345
--0.00753885

--4
DROP INDEX IX_TEST_ZAWARTOSC ON test;

SELECT Zawartosc,Zawartosc2 FROM test WHERE Zawartosc=12345;
--0.449577

CREATE NONCLUSTERED INDEX IX_TEST_ZAWARTOSCX2
ON TEST (Zawartosc,Zawartosc2);

SELECT Zawartosc,Zawartosc2 FROM test WHERE Zawartosc=12345;
--0.00328378

--5
DROP INDEX IX_TEST_ZAWARTOSCX2 ON test;

SELECT * FROM test WHERE Zawartosc BETWEEN 10000 AND 20000;
--0.449577

CREATE NONCLUSTERED INDEX IX_TEST_ZAWARTOSC
ON TEST (Zawartosc);

SELECT * FROM test WHERE Zawartosc BETWEEN 10000 AND 20000;
--0.449577

DROP INDEX IX_TEST_ZAWARTOSC ON test;

CREATE CLUSTERED INDEX IX_TEST_ZAWARTOSCCLUST
ON TEST (Zawartosc);

SELECT * FROM test WHERE Zawartosc BETWEEN 10000 AND 20000;
--0.0357564

--6
DROP INDEX IX_TEST_ZAWARTOSCCLUST ON test;

SELECT * FROM test ORDER BY Zawartosc
--7.96764

CREATE NONCLUSTERED INDEX IX_TEST_ZAWARTOSC
ON TEST (Zawartosc);

SELECT * FROM test ORDER BY Zawartosc
--7.96764

DROP INDEX IX_TEST_ZAWARTOSC ON test;

CREATE CLUSTERED INDEX IX_TEST_ZAWARTOSCCLUST
ON TEST (Zawartosc);

SELECT * FROM test ORDER BY Zawartosc
--0.33254

--7
SET IMPLICIT_TRANSACTIONS ON -- wyłączenie automatycznego zatwierdzania
CREATE TABLE Osoba (Id INT, Nazwisko VARCHAR(50))

COMMIT

INSERT INTO Osoba VALUES (1, 'Lenkiewicz')
INSERT INTO Osoba VALUES (2, 'Kowalski')
SELECT * FROM Osoba -- powinniśmy zobaczyć dwie osoby

ROLLBACK

SELECT * FROM Osoba -- powinniśmy zobaczyć pustą tabelę
INSERT INTO Osoba VALUES (3, 'Iksiński')

COMMIT

SELECT * FROM Osoba -- powinniśmy zobaczyć jedną osobę

DROP TABLE OSOBA;

--8
SET IMPLICIT_TRANSACTIONS OFF
CREATE TABLE Osoba (Id INT, Nazwisko VARCHAR(50))

COMMIT

INSERT INTO Osoba VALUES (1, 'Lenkiewicz')
INSERT INTO Osoba VALUES (2, 'Kowalski')
SELECT * FROM Osoba -- powinniśmy zobaczyć dwie osoby

ROLLBACK

SELECT * FROM Osoba -- powinniśmy zobaczyć pustą tabelę
INSERT INTO Osoba VALUES (3, 'Iksiński')

COMMIT

SELECT * FROM Osoba -- powinniśmy zobaczyć jedną osobę

--9
SET IMPLICIT_TRANSACTIONS ON
SELECT * FROM Osoba

UPDATE Osoba SET Nazwisko = 'Igrekowski' WHERE Id = 3

COMMIT

--10
--TO DLA PIERWSZEGO OKNA
SET IMPLICIT_TRANSACTIONS ON
SELECT * FROM Osoba

UPDATE Osoba SET Nazwisko = 'Igrekowski' WHERE Id = 3

COMMIT

--TO DLA 2 OKNA
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

SELECT * FROM Osoba

--11
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET IMPLICIT_TRANSACTIONS ON
COMMIT

SELECT * FROM Test

INSERT INTO Test (Zawartosc, Zawartosc2) VALUES (12345, 56789)
