--1
SELECT * FROM OSOBA
WHERE NAZWISKO NOT LIKE 'L%';
--2
SELECT PRZEDMIOT, COUNT(*) AS LICZBA_OCEN FROM OCENY
JOIN PRZEDMIOTY P on OCENY.PRZEDMIOT_ID = P.PRZEDMIOT_ID
GROUP BY PRZEDMIOT
HAVING COUNT(*) !=1;
--3
SELECT DISTINCT PRZEDMIOT, PRZEDMIOTY.PRZEDMIOT_ID FROM PRZEDMIOTY
LEFT JOIN OCENY O on PRZEDMIOTY.PRZEDMIOT_ID = O.PRZEDMIOT_ID
WHERE OCENA IS NULL;
--4
SELECT NAZWISKO, IMIE, S.OSOBA_ID,
       (MAX(OCENA) FROM SELECT OSOBA_ID, AVG(OCENA) FROM STUDENCI
                                                   JOIN OCENY O on STUDENCI.OSOBA_ID = O.STUDENT
                                                   GROUP BY OSOBA_ID) AS SREDNIA)
                  FROM STUDENCI S
JOIN OSOBA O on O.OSOBA_ID = S.OSOBA_ID
JOIN OCENY O on S.OSOBA_ID = O.STUDENT
GROUP BY S.OSOBA_ID, O.STUDENT, NAZWISKO, IMIE;

Select Max(avg_ocena), imie, nazwisko from (Select AVG(Ocena) as avg_ocena,
Imie as imie, Nazwisko as nazwisko from Oceny  join Studenci S on S.Osoba_Id = Oceny.Student
    join Osoby O on O.Osoba_Id = S.Osoba_Id
group by Imie, Nazwisko) as max

--5
SELECT IMIE,NAZWISKO FROM OSOBA
JOIN DYDAKTYCY D on OSOBA.OSOBA_ID = D.OSOBA_ID
WHERE NOT EXISTS(SELECT IMIE, NAZWISKO FROM STUDENCI S WHERE D.OSOBA_ID = S.OSOBA_ID);