--1
CREATE OR REPLACE PROCEDURE ZAD1 IS
    AVGGRADE INT;
    STUDNENTID INT;
    CURSOR SECOND IS SELECT IDSTUDENTA FROM STUDENT WHERE ROK = 2;
BEGIN
    OPEN SECOND;
    LOOP
        FETCH SECOND INTO STUDNENTID;
        SELECT AVG(WARTOSC) INTO AVGGRADE FROM OCENA WHERE IDSTUDENTA = STUDNENTID;
        DBMS_OUTPUT.PUT_LINE('ID STUDENTA: ' || STUDNENTID || ' SREDNIA:' || AVGGRADE);

        IF AVGGRADE < 2.5 THEN
            DELETE FROM OCENA WHERE IdStudenta = STUDNENTID;
            DBMS_OUTPUT.PUT_LINE('USUNIETO OCENE STUDENTA O ID: ' || STUDNENTID);
            DELETE FROM STUDENT WHERE IdStudenta = STUDNENTID;
            DBMS_OUTPUT.PUT_LINE('USUNIETO STUDENTA O ID: ' || STUDNENTID);
        end if;

        EXIT WHEN SECOND%NOTFOUND;
    end loop;
END;

CALL ZAD1();

--2
CREATE OR REPLACE TRIGGER ZAD2 AFTER INSERT OR UPDATE ON STUDENT
    FOR EACH ROW
BEGIN
    IF UPDATING THEN
        IF :NEW.ROK > :OLD.ROK+1 THEN
           RAISE_APPLICATION_ERROR(-20001,'ROK NIE MOZE BYC ZWIEKSZONY O WIECEJ NIZ 1 W GORE!');
        end if;
    end if;
    IF INSERTING THEN
        IF :NEW.ROK > 5 THEN
            RAISE_APPLICATION_ERROR(-20001,'WPISANY ROK NIE MOZE BYC WIEKSZY NIZ 5!');
        end if;
    end if;
END;