--1
CREATE PROCEDURE DOKONAJREZERWACJI @IDGOSCIA INT, @NRPOKOJU INT, @DATAOD DATE,
@DATADO DATE AS
BEGIN
    --JAK GOSC NIE ISTNIEJE I POKOJ NIE ISTNIEJE
    IF NOT EXISTS(SELECT * FROM Rezerwacja WHERE IdGosc = @IDGOSCIA)
        BEGIN
            THROW 50003, 'PODANE ID GOSCIA NIE ISTNIEJE!',2;
        END;
    IF NOT EXISTS(SELECT * FROM Rezerwacja WHERE NrPokoju = @NRPOKOJU)
        BEGIN
            THROW 50004, 'PODANY NR POKOJU NIE ISTNIEJE!',2;
        END;
    ELSE
        BEGIN
            --JEZELI NIE ISTNIEJE REZERWACJA NA TEN TERMIN NA DANY POKOJ
            IF NOT EXISTS(SELECT * FROM Rezerwacja WHERE NrPokoju = @NRPOKOJU AND DataOd = @DATAOD AND DataDo = @DATADO)
                BEGIN
                    DECLARE @NRREZERWACJI INT = (SELECT MAX(IdRezerwacja) FROM Rezerwacja) + 1;

                    INSERT INTO Rezerwacja(IDREZERWACJA, DATAOD, DATADO, IDGOSC, NRPOKOJU, ZAPLACONA)
                    VALUES(@NRREZERWACJI,@DATAOD,@DATADO,@IDGOSCIA,@NRPOKOJU,0);
                    PRINT 'DODANO REZERWACJE DLA POKOJU ' + CAST(@NRPOKOJU AS VARCHAR);
                END;
            --JEZELI ISTNEJE REZERWACJA NA TEN TERMIN NA DANY POKOJ
            ELSE
                BEGIN
                    THROW 50002, 'DANY POKOJ JEST JUZ ZAREZERWOWANY!',2;
                END;
        END;

END;

EXEC DOKONAJREZERWACJI 1, 101, '2022-12-13','2022-12-13';
EXEC DOKONAJREZERWACJI 1,305,'2022-12-13','2022-12-13';

--2
    CREATE trigger CHECKGOSC
        on Rezerwacja
        for DELETE
        AS
    BEGIN
        DECLARE @DELETEDID INT = (SELECT IdGosc FROM deleted)
        --JEZELI NIE MA JUZ WIECEJ REZERWACJI OD GOSCIA = NIE MA REZERWACJI Z JEGO ID W TABELI REZERWACJA
        IF NOT EXISTS(SELECT * FROM Rezerwacja WHERE Rezerwacja.IdGosc = @DELETEDID)
            BEGIN
                --USUN Z TABELI GOSC JEGO DANE
                DELETE FROM GOSC WHERE IdGosc = @DELETEDID;
                PRINT 'USUNIEO DANE UZYTKOWNIKA Z TABELI GOSC'
            END;
    END;


DELETE FROM Rezerwacja WHERE IdGosc = 5;
